# This is a generic set of Rubocop style configurations.
#
# These configurations are intended to be inherited and overriden
# as needed by any ruby project that pulls them in.
#
# Note that many rules under "Lint/" have had their severity raised to "error".
# We currently consider violations of such rules to require *immediate*
# resolution as they represent broken or dangerously invalid code.
#
# All other violations are categorized with a severity of "warning" or lower.
# When first introducing these rules to your project, it is recommended to
# set Rubocop's "--failure-threshold" option to "error" until all warnings
# are addressed.
#
# It is strongly discouraged to leverage Rubocop's exclude/ignore settings
# for violations you intend to fix in the future.
# These exclusion rules tend to outlast the code they reference
# and should be considered an anti-pattern.
#
# @see https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  # This should be overriden in the project `.rubocop.yml` file
  TargetRubyVersion: 2.4

## Lint

Lint/CircularArgumentReference:
  Severity: error

Lint/Debugger:
  Severity: error

Lint/DuplicateMethods:
  Severity: error

Lint/DuplicatedKey:
  Severity: error

Lint/EachWithObjectArgument:
  Severity: error

Lint/EndAlignment:
  AlignWith: start_of_line

Lint/Eval:
  Severity: error

Lint/UnreachableCode:
  Severity: error

Lint/UselessComparison:
  Severity: error

## Metrics

Metrics/LineLength:
  Max: 120
  Severity: refactor

Metrics/MethodLength:
  Severity: refactor

## Layout

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Layout/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Layout/ClassAndModuleChildren:
  Enabled: false

Layout/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
